version: '3.4'

services:
  ecommerceapiproducts:
    image: ecommerceapiproducts
    build:
      context: .
      dockerfile: ECommerce.Api.Products/Dockerfile
    ports:
      - 22496
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:22496
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  ecommerceapicustomers:
    image: ecommerceapicustomers
    build:
      context: .
      dockerfile: ECommerce.Api.Customers/Dockerfile
    ports:
      - 40147
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:40147
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
