version: '3.4'

services:
  ecommerceapiproducts:
    image: ecommerceapiproducts
    build:
      context: .
      dockerfile: ECommerce.Api.Products/Dockerfile
    ports:
      - "22496:22496"
  ecommerceapicustomers:
    image: ecommerceapicustomers
    build:
      context: .
      dockerfile: ECommerce.Api.Customers/Dockerfile
    ports:
      - "40147:40147"