version: '3.4'

services:
  products:
    image: rcontrerasnet/ecommerceapiproducts:latest
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"
  customers:
    image: rcontrerasnet/ecommerceapicustomers:latest
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"
  orders:
    image: rcontrerasnet/ecommerceapiorders:latest
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"
  search:
    image: rcontrerasnet/ecommerceapisearch:latest
    ports:
      - "5000:80"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Customers=http://10.0.0.4:20009/ecommercerc/customers/
      - Services__Orders=http://10.0.0.4:20008/ecommercerc/orders/
      - Services__Products=http://10.0.0.4:20010/ecommercerc/products/
