version: '3.4'

services:
  products:
    image: ecommercerc/ecommerceapiproducts:latest
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"
  customers:
    image: ecommercerc/ecommerceapicustomers:latest
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"
  orders:
    image: ecommercerc/ecommerceapiorders:latest
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"
  search:
    image: ecommercerc/ecommerceapisearch:latest
    ports:
      - "5000:80"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Products=http://10.0.0.4/ecommercerc/products/
      - Services__Customers=http://10.0.0.4/ecommercerc/customers/
      - Services__Orders=http://10.0.0.4/ecommercerc/orders/