version: '3.4'

services:
  ecommerceapi:
    image: ecommerceapi
    build:
      context: .
      dockerfile: ECommerce.Api.Products/Dockerfile
    ports:
      - 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
